"""empty message

Revision ID: 3bc71dfafa1c
Revises: 
Create Date: 2023-12-02 22:21:21.282475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc71dfafa1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(length=50), nullable=True),
    sa.Column('place', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_place'), ['place'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_stockname'), ['stockname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_stockname'))
        batch_op.drop_index(batch_op.f('ix_stock_place'))
        batch_op.drop_index(batch_op.f('ix_stock_hostname'))

    op.drop_table('stock')
    # ### end Alembic commands ###
