"""empty message

Revision ID: d200fd45b2bb
Revises: 3bc71dfafa1c
Create Date: 2023-12-03 12:34:38.466941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd200fd45b2bb'
down_revision = '3bc71dfafa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_stockname')
        batch_op.create_index(batch_op.f('ix_stock_stockname'), ['stockname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_stockname'))
        batch_op.create_index('ix_stock_stockname', ['stockname'], unique=False)

    # ### end Alembic commands ###
